# Generated by Django 6.1.1 on 2026-09-12 21:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivoRentaVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('cantidad', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('precio', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('moneda', models.CharField(choices=[('ARS', 'Pesos argentinos'), ('USD', 'Dólares estadounidenses')], max_length=3)),
                ('cartera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='portfolio.cartera')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivoRentaFija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('cantidad', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('precio', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('moneda', models.CharField(choices=[('ARS', 'Pesos argentinos'), ('USD', 'Dólares estadounidenses')], max_length=3)),
                ('cartera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='portfolio.cartera')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cartera',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carteras', to='portfolio.perfil'),
        ),
    ]
